
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "southamerica-east1-docker.pkg.dev/tienda-microservicios-464423/image-registry/product-ms",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-east1-docker.pkg.dev/tienda-microservicios-464423/image-registry/product-ms",
      ]

serviceAccount: "905360638325-compute@developer.gserviceaccount.com"

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET